config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  resources :books

end

app/models/book.rb
class Book < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.create book_params
    redirect_to root_path
  end

  def show
    @book = Book.find params[:id]
  end

  def edit
    @book = Book.find params[:id]
  end

  def update
    @book = Book.find params[:id]
    @book.update_attributes book_params
    redirect_to root_path
  end

  def destroy
    @book = Book.find params[:id]
    @book.destroy
    redirect_to root_path
  end

  private
  def book_params
    params.require(:book).permit(
      :title,
      :label
    )
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @books = Book.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/books/index.html.haml
Hello!

app/views/home/index.html.haml
.intro-wallpaper
  .row
    .container
      .col-xs-12.intro-words
        %h1 Welcome back Adam
        = link_to "View Books", books_path, class: 'btn btn-danger'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PoetryBook</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>